# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
        
    - name: Install dependencies
        run: |
          go get -u github.com/gin-gonic/gin
          go get -u gorm.io/gorm
          go get -u gorm.io/driver/mysql
    - name: Import go.sum
      - name: Setup Go
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache-dependency-path: subdir/go.sum

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
