# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/myproject
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: ${{ env.GOPATH }}/src/myproject

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
        
    - name: Set up dependency
      run: |
        go get .
        go get -u github.com/gin-gonic/gin
        go get -u gorm.io/gorm
        go get -u gorm.io/driver/mysql
      env:
        GOPATH: /home/runner/work/woodpecker/go

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
