# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Fix Test Case

on:
  push:
    branches: [ "fix/test-case" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/myproject
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ env.GOPATH }}/src/myproject
          ref: main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Set up dependency
        run: |
          go mod download
        env:
          GOPATH: /home/runner/work/woodpecker/go

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...